collections:
  work:
    output: true
    order:
      - eligibilityhub.md
      - weeklyinterviews.md
      - livealerts.md
      - nandos.md
      - storystudio.md
      - darkpatterns.md
      - uxcompanion.md
  play:
    output: true
    order:
      - yearbooks.md
      - minipainting.md
      - iran.md
      - mariokart.md
      - dune.md
      - scglossary.md
  posts:
    permalink: /blog/:title.html

defaults:
  - scope:
      path: ""
      type: "work"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "play"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:title/