collections:
  work:
    output: true
  play:
    output: true
  posts:
    permalink: /blog/:title.html

defaults:
  - scope:
      path: ""
      type: "work"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "play"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:title/